2024-01-11 14:01:12,724 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2024-01-11 14:01:12,789 MainThread udi_interface      INFO     __init__:<module>: UDI interface initializing
2024-01-11 14:01:12,799 MainThread udi_interface      INFO     __init__:<module>: User=admin
2024-01-11 14:01:12,800 MainThread udi_interface      INFO     __init__:<module>: Home=/home/admin
2024-01-11 14:01:12,800 MainThread udi_interface      INFO     __init__:<module>: Node Server Path=/usr/home/admin/workspace/plugin-dev/audio-player
2024-01-11 14:01:12,801 MainThread udi_interface      INFO     __init__:<module>: PG3INIT=Not set
2024-01-11 14:01:12,801 MainThread udi_interface      INFO     __init__:<module>: Loading interface module
2024-01-11 14:01:13,124 MainThread udi_interface      INFO     interface:<module>: Loading MQTT module
2024-01-11 14:01:13,165 MainThread udi_interface      INFO     interface:<module>: MQTT module loaded
2024-01-11 14:01:14,012 MainThread udi_interface      INFO     __init__:<module>: Loading udi_interface module
2024-01-11 14:01:14,015 MainThread udi_interface      INFO     __init__:<module>: Loading node module
2024-01-11 14:01:14,015 MainThread udi_interface      INFO     __init__:<module>: Loading custom module
2024-01-11 14:01:14,016 MainThread udi_interface      INFO     __init__:<module>: Loading isy module
2024-01-11 14:01:14,016 MainThread udi_interface      INFO     __init__:<module>: UDI interface initialized
2024-01-11 14:01:14,016 MainThread udi_interface      INFO     __init__:<module>: UDI Python Interface for Polyglot version 3 3.2.2 Starting...
2024-01-11 14:01:14,071 MainThread udi_interface.interface CRITICAL interface:__init__: Failed to parse init. Exiting...
2024-01-11 14:01:31,941 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2024-01-11 14:01:31,954 MainThread udi_interface      INFO     __init__:<module>: UDI interface initializing
2024-01-11 14:01:31,956 MainThread udi_interface      INFO     __init__:<module>: User=admin
2024-01-11 14:01:31,957 MainThread udi_interface      INFO     __init__:<module>: Home=/home/admin
2024-01-11 14:01:31,957 MainThread udi_interface      INFO     __init__:<module>: Node Server Path=/usr/home/admin/workspace/plugin-dev/audio-player
2024-01-11 14:01:31,960 MainThread udi_interface      INFO     __init__:<module>: PG3INIT=eyJ1dWlkIjoiMDA6MjE6Yjk6MjY6MjY6MjYiLCJwcm9maWxlTnVtIjoxLCJsb2dMZXZlbCI6IklORk8iLCJ0b2tlbiI6IlRaSCEpKEUwTE5VeCpHR2kiLCJtcXR0SG9zdCI6ImxvY2FsaG9zdCIsIm1xdHRQb3J0Ijo4ODgzLCJzZWN1cmUiOjEsImlzUEczeCI6dHJ1ZSwicGczVmVyc2lvbiI6IjMuMi4xNyIsImlzeVZlcnNpb24iOiI1LjguMCIsImVkaXRpb24iOiJGcmVlIn0=
2024-01-11 14:01:31,961 MainThread udi_interface      INFO     __init__:<module>: Loading interface module
2024-01-11 14:01:32,340 MainThread udi_interface      INFO     interface:<module>: Loading MQTT module
2024-01-11 14:01:32,437 MainThread udi_interface      INFO     interface:<module>: MQTT module loaded
2024-01-11 14:01:33,399 MainThread udi_interface      INFO     __init__:<module>: Loading udi_interface module
2024-01-11 14:01:33,402 MainThread udi_interface      INFO     __init__:<module>: Loading node module
2024-01-11 14:01:33,402 MainThread udi_interface      INFO     __init__:<module>: Loading custom module
2024-01-11 14:01:33,403 MainThread udi_interface      INFO     __init__:<module>: Loading isy module
2024-01-11 14:01:33,403 MainThread udi_interface      INFO     __init__:<module>: UDI interface initialized
2024-01-11 14:01:33,403 MainThread udi_interface      INFO     __init__:<module>: UDI Python Interface for Polyglot version 3 3.2.2 Starting...
2024-01-11 14:01:33,473 MainThread udi_interface.interface INFO     interface:__init__: Initialization received from Polyglot V3 3.2.17  [ISY: 5.8.0, Slot: 1]
2024-01-11 14:01:33,474 MainThread udi_interface.interface INFO     interface:__init__: Connect: Network Interface: {'addr': '172.26.18.3', 'netmask': '255.255.255.0', 'broadcast': '172.26.18.255'}
2024-01-11 14:01:33,484 Interface  udi_interface.interface INFO     interface:_startMqtt: Connecting to MQTT... localhost:8883
2024-01-11 14:01:33,485 MainThread udi_interface.interface WARNING  interface:_get_server_data: get_server_data: failed to read file server.json: [Errno 2] No such file or directory: 'server.json'
2024-01-11 14:01:33,486 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:01:33,495 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:01:36,487 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:01:36,537 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:01:39,490 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:01:39,546 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:01:42,492 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:01:42,554 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:01:45,493 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:01:45,561 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:01:48,503 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:01:48,572 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:01:51,506 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:01:51,578 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:01:54,508 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:01:54,584 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:01:57,517 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:01:57,593 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:00,520 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:02:00,601 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:03,521 MainThread udi_interface.interface ERROR    interface:send: MQTT Send timeout :: {'config': {'version': '1.0.2', 'requestId': False}}.
2024-01-11 14:02:03,522 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getAll': {}}
2024-01-11 14:02:03,610 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:06,524 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getAll': {}}
2024-01-11 14:02:06,633 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:09,525 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getAll': {}}
2024-01-11 14:02:09,644 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:12,526 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getAll': {}}
2024-01-11 14:02:12,651 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:15,528 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getAll': {}}
2024-01-11 14:02:15,657 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:18,529 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getAll': {}}
2024-01-11 14:02:18,666 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:21,531 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getAll': {}}
2024-01-11 14:02:21,672 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:24,534 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getAll': {}}
2024-01-11 14:02:24,680 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:27,536 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getAll': {}}
2024-01-11 14:02:27,686 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:30,537 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getAll': {}}
2024-01-11 14:02:30,695 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:33,538 MainThread udi_interface.interface ERROR    interface:send: MQTT Send timeout :: {'getAll': {}}.
2024-01-11 14:02:33,539 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getNsInfo': {}}
2024-01-11 14:02:33,701 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:36,544 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getNsInfo': {}}
2024-01-11 14:02:36,707 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:39,545 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getNsInfo': {}}
2024-01-11 14:02:39,718 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:42,548 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getNsInfo': {}}
2024-01-11 14:02:42,741 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:45,550 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getNsInfo': {}}
2024-01-11 14:02:45,748 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:48,552 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getNsInfo': {}}
2024-01-11 14:02:48,759 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:51,553 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getNsInfo': {}}
2024-01-11 14:02:51,766 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:54,556 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getNsInfo': {}}
2024-01-11 14:02:54,772 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:02:57,560 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getNsInfo': {}}
2024-01-11 14:02:57,782 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:00,561 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'getNsInfo': {}}
2024-01-11 14:03:00,788 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:03,565 MainThread udi_interface.interface ERROR    interface:send: MQTT Send timeout :: {'getNsInfo': {}}.
2024-01-11 14:03:03,567 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'set': [{'key': 'customparamsdoc', 'value': ''}]}
2024-01-11 14:03:03,793 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:06,569 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'set': [{'key': 'customparamsdoc', 'value': ''}]}
2024-01-11 14:03:06,799 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:09,571 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'set': [{'key': 'customparamsdoc', 'value': ''}]}
2024-01-11 14:03:09,808 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:12,574 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'set': [{'key': 'customparamsdoc', 'value': ''}]}
2024-01-11 14:03:12,815 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:15,576 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'set': [{'key': 'customparamsdoc', 'value': ''}]}
2024-01-11 14:03:15,821 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:18,594 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'set': [{'key': 'customparamsdoc', 'value': ''}]}
2024-01-11 14:03:18,837 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:21,595 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'set': [{'key': 'customparamsdoc', 'value': ''}]}
2024-01-11 14:03:21,842 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:24,596 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'set': [{'key': 'customparamsdoc', 'value': ''}]}
2024-01-11 14:03:24,856 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:27,604 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'set': [{'key': 'customparamsdoc', 'value': ''}]}
2024-01-11 14:03:27,861 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:30,605 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'set': [{'key': 'customparamsdoc', 'value': ''}]}
2024-01-11 14:03:30,867 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:32,088 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2024-01-11 14:03:32,089 MainThread udi_interface      INFO     __init__:<module>: UDI interface initializing
2024-01-11 14:03:32,089 MainThread udi_interface      INFO     __init__:<module>: User=admin
2024-01-11 14:03:32,090 MainThread udi_interface      INFO     __init__:<module>: Home=/home/admin
2024-01-11 14:03:32,091 MainThread udi_interface      INFO     __init__:<module>: Node Server Path=/usr/home/admin/workspace/plugin-dev/audio-player
2024-01-11 14:03:32,092 MainThread udi_interface      INFO     __init__:<module>: PG3INIT=eyJ1dWlkIjoiMDA6MjE6Yjk6MjY6MjY6MjYiLCJwcm9maWxlTnVtIjoyLCJsb2dMZXZlbCI6IklORk8iLCJ0b2tlbiI6ImMmODAtY1psQjRNQ1RQVU8iLCJtcXR0SG9zdCI6ImxvY2FsaG9zdCIsIm1xdHRQb3J0Ijo4ODgzLCJzZWN1cmUiOjEsImlzUEczeCI6dHJ1ZSwicGczVmVyc2lvbiI6IjMuMi4xNyIsImlzeVZlcnNpb24iOiI1LjguMCIsImVkaXRpb24iOiJGcmVlIn0=
2024-01-11 14:03:32,092 MainThread udi_interface      INFO     __init__:<module>: Loading interface module
2024-01-11 14:03:32,153 MainThread udi_interface      INFO     interface:<module>: Loading MQTT module
2024-01-11 14:03:32,200 MainThread udi_interface      INFO     interface:<module>: MQTT module loaded
2024-01-11 14:03:32,476 MainThread udi_interface      INFO     __init__:<module>: Loading udi_interface module
2024-01-11 14:03:32,477 MainThread udi_interface      INFO     __init__:<module>: Loading node module
2024-01-11 14:03:32,477 MainThread udi_interface      INFO     __init__:<module>: Loading custom module
2024-01-11 14:03:32,478 MainThread udi_interface      INFO     __init__:<module>: Loading isy module
2024-01-11 14:03:32,478 MainThread udi_interface      INFO     __init__:<module>: UDI interface initialized
2024-01-11 14:03:32,478 MainThread udi_interface      INFO     __init__:<module>: UDI Python Interface for Polyglot version 3 3.2.2 Starting...
2024-01-11 14:03:32,507 MainThread udi_interface.interface INFO     interface:__init__: Initialization received from Polyglot V3 3.2.17  [ISY: 5.8.0, Slot: 2]
2024-01-11 14:03:32,508 MainThread udi_interface.interface INFO     interface:__init__: Connect: Network Interface: {'addr': '172.26.18.3', 'netmask': '255.255.255.0', 'broadcast': '172.26.18.255'}
2024-01-11 14:03:32,510 Interface  udi_interface.interface INFO     interface:_startMqtt: Connecting to MQTT... localhost:8883
2024-01-11 14:03:32,511 MainThread udi_interface.interface WARNING  interface:_get_server_data: get_server_data: failed to read file server.json: [Errno 2] No such file or directory: 'server.json'
2024-01-11 14:03:32,511 Interface  udi_interface.interface INFO     interface:_startMqtt: Using SSL cert: 0021b9262626_2.cert key: 0021b9262626_2.key ca: /usr/local/etc/ssl/certs/ud.ca.cert
2024-01-11 14:03:32,511 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:03:32,560 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Connected with result code 0 (Success)
2024-01-11 14:03:32,561 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Subscribing to topic: udi/pg3/ns/clients/00:21:b9:26:26:26_2 -  MID: 2 Result: 0
2024-01-11 14:03:32,601 MQTT       udi_interface.interface INFO     interface:_subscribe: MQTT Subscribed Succesfully for Message ID: 2 - QoS: (0,)
2024-01-11 14:03:33,607 MainThread udi_interface.interface ERROR    interface:send: MQTT Send timeout :: {'set': [{'key': 'customparamsdoc', 'value': ''}]}.
2024-01-11 14:03:33,879 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:35,598 Thread-1   udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2024-01-11 14:03:35,599 Thread-1   udi_interface      INFO     audio-player:parameterHandler: we are using ./sounds as path
2024-01-11 14:03:35,599 Thread-1   udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2024-01-11 14:03:35,600 MQTT       udi_interface.interface INFO     interface:_message: custom data response {'customparamsdoc': ''}
2024-01-11 14:03:35,601 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = customparamsdoc
2024-01-11 14:03:35,602 Thread-1   udi_interface.interface INFO     interface:updateProfile: Sending Install Profile command to Polyglot.
2024-01-11 14:03:35,603 Thread-1   udi_interface      INFO     audio-player:addAudioNode: Adding AudioPlayer node
2024-01-11 14:03:35,603 Thread-1   udi_interface.interface WARNING  interface:db_getNodeDrivers: 0 not found in database.
2024-01-11 14:03:35,603 Thread-1   udi_interface.interface INFO     interface:addNode: Adding node AudioPlayer(0) [None]
2024-01-11 14:03:35,620 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = notices
2024-01-11 14:03:35,700 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = notices
2024-01-11 14:03:35,761 MQTT       udi_interface.interface INFO     interface:_message: Profile installation finished
2024-01-11 14:03:36,123 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: ST to 0 UOM 25
2024-01-11 14:03:36,163 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: GV0 to 0 UOM 25
2024-01-11 14:03:36,885 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:39,890 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:42,902 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:45,912 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:48,916 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:51,933 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:54,938 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:03:57,785 MainThread udi_interface      ERROR    udi_interface:write: Exception ignored in:
2024-01-11 14:03:57,785 MainThread udi_interface      ERROR    udi_interface:write: <module 'threading' from '/usr/local/lib/python3.9/threading.py'>
2024-01-11 14:03:57,786 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2024-01-11 14:03:57,786 MainThread udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.9/threading.py", line 1477, in _shutdown
2024-01-11 14:03:57,787 MainThread udi_interface      ERROR    udi_interface:write: lock.acquire()
2024-01-11 14:03:57,787 MainThread udi_interface      ERROR    udi_interface:write: KeyboardInterrupt
2024-01-11 14:03:57,788 MainThread udi_interface      ERROR    udi_interface:write: :
2024-01-11 14:03:57,943 Interface  udi_interface.interface ERROR    interface:_startMqtt: MQTT Connection SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134), Will retry in a few seconds.
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 544, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1742, in loop_forever
    self.reconnect()
  File "/home/admin/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1134)
2024-01-11 14:04:53,446 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2024-01-11 14:04:53,449 MainThread udi_interface      INFO     __init__:<module>: UDI interface initializing
2024-01-11 14:04:53,450 MainThread udi_interface      INFO     __init__:<module>: User=admin
2024-01-11 14:04:53,450 MainThread udi_interface      INFO     __init__:<module>: Home=/home/admin
2024-01-11 14:04:53,451 MainThread udi_interface      INFO     __init__:<module>: Node Server Path=/usr/home/admin/workspace/plugin-dev/audio-player
2024-01-11 14:04:53,451 MainThread udi_interface      INFO     __init__:<module>: PG3INIT=eyJ1dWlkIjoiMDA6MjE6Yjk6MjY6MjY6MjYiLCJwcm9maWxlTnVtIjoyLCJsb2dMZXZlbCI6IklORk8iLCJ0b2tlbiI6ImMmODAtY1psQjRNQ1RQVU8iLCJtcXR0SG9zdCI6ImxvY2FsaG9zdCIsIm1xdHRQb3J0Ijo4ODgzLCJzZWN1cmUiOjEsImlzUEczeCI6dHJ1ZSwicGczVmVyc2lvbiI6IjMuMi4xNyIsImlzeVZlcnNpb24iOiI1LjguMCIsImVkaXRpb24iOiJGcmVlIn0=
2024-01-11 14:04:53,452 MainThread udi_interface      INFO     __init__:<module>: Loading interface module
2024-01-11 14:04:53,636 MainThread udi_interface      INFO     interface:<module>: Loading MQTT module
2024-01-11 14:04:53,673 MainThread udi_interface      INFO     interface:<module>: MQTT module loaded
2024-01-11 14:04:54,294 MainThread udi_interface      INFO     __init__:<module>: Loading udi_interface module
2024-01-11 14:04:54,296 MainThread udi_interface      INFO     __init__:<module>: Loading node module
2024-01-11 14:04:54,296 MainThread udi_interface      INFO     __init__:<module>: Loading custom module
2024-01-11 14:04:54,297 MainThread udi_interface      INFO     __init__:<module>: Loading isy module
2024-01-11 14:04:54,297 MainThread udi_interface      INFO     __init__:<module>: UDI interface initialized
2024-01-11 14:04:54,297 MainThread udi_interface      INFO     __init__:<module>: UDI Python Interface for Polyglot version 3 3.2.2 Starting...
2024-01-11 14:04:54,336 MainThread udi_interface.interface INFO     interface:__init__: Initialization received from Polyglot V3 3.2.17  [ISY: 5.8.0, Slot: 2]
2024-01-11 14:04:54,336 MainThread udi_interface.interface INFO     interface:__init__: Connect: Network Interface: {'addr': '172.26.18.3', 'netmask': '255.255.255.0', 'broadcast': '172.26.18.255'}
2024-01-11 14:04:54,339 MainThread udi_interface.interface WARNING  interface:_get_server_data: get_server_data: failed to read file server.json: [Errno 2] No such file or directory: 'server.json'
2024-01-11 14:04:54,340 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:04:54,340 Interface  udi_interface.interface INFO     interface:_startMqtt: Connecting to MQTT... localhost:8883
2024-01-11 14:04:54,341 Interface  udi_interface.interface INFO     interface:_startMqtt: Using SSL cert: 0021b9262626_2.cert key: 0021b9262626_2.key ca: /usr/local/etc/ssl/certs/ud.ca.cert
2024-01-11 14:04:54,392 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Connected with result code 0 (Success)
2024-01-11 14:04:54,393 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Subscribing to topic: udi/pg3/ns/clients/00:21:b9:26:26:26_2 -  MID: 2 Result: 0
2024-01-11 14:04:54,433 MQTT       udi_interface.interface INFO     interface:_subscribe: MQTT Subscribed Succesfully for Message ID: 2 - QoS: (0,)
2024-01-11 14:04:57,389 Thread-6   udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2024-01-11 14:04:57,390 Thread-6   udi_interface      INFO     audio-player:parameterHandler: we are using ./sounds as path
2024-01-11 14:04:57,390 Thread-6   udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2024-01-11 14:04:57,392 Thread-6   udi_interface.interface INFO     interface:updateProfile: Sending Install Profile command to Polyglot.
2024-01-11 14:04:57,402 MQTT       udi_interface.interface INFO     interface:_message: custom data response {'customparamsdoc': ''}
2024-01-11 14:04:57,441 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = customparamsdoc
2024-01-11 14:04:57,482 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = notices
2024-01-11 14:04:57,484 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = notices
2024-01-11 14:04:57,561 MQTT       udi_interface.interface INFO     interface:_message: Profile installation finished
2024-01-11 14:05:05,308 Command    udi_interface.interface ERROR    interface:_handleInput: _parseInput: node address 0 does not exist. {'address': '0', 'cmd': 'PLAY', 'query': {'PLAYLIST.uom25': '4'}}
2024-01-11 14:05:08,735 Thread-6   udi_interface      INFO     audio-player:addAudioNode: Adding AudioPlayer node
2024-01-11 14:05:08,738 Thread-6   udi_interface.interface INFO     interface:addNode: Adding node AudioPlayer(0) [None]
2024-01-11 14:05:09,060 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: ST to 0 UOM 25
2024-01-11 14:05:09,101 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: GV0 to 0 UOM 25
2024-01-11 14:05:21,367 Command    udi_interface      INFO     audio-player:processCommand: Got command: {'address': '0', 'cmd': 'STOP', 'query': {}}
2024-01-11 14:05:33,021 Command    udi_interface      INFO     audio-player:processCommand: Got command: {'address': '0', 'cmd': 'PLAY', 'query': {'PLAYLIST.uom25': '4'}}
2024-01-11 14:05:33,023 Command    udi_interface      INFO     audio-player:processCommand: Playing #4:./sounds/fantasy.mp3
2024-01-11 14:05:33,024 Command    udi_interface      ERROR    audio-player:processCommand: local variable 'audio_player_thread' referenced before assignment
2024-01-11 14:05:33,026 Thread-8   udi_interface      INFO     audio-player:poll: short poll
2024-01-11 14:05:46,785 Command    udi_interface      INFO     audio-player:processCommand: Got command: {'address': '0', 'cmd': 'PLAY', 'query': {'PLAYLIST.uom25': '4'}}
2024-01-11 14:05:55,251 Command    udi_interface      INFO     audio-player:processCommand: Playing #4:./sounds/fantasy.mp3
2024-01-11 14:06:58,261 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2024-01-11 14:06:58,263 MainThread udi_interface      INFO     __init__:<module>: UDI interface initializing
2024-01-11 14:06:58,264 MainThread udi_interface      INFO     __init__:<module>: User=admin
2024-01-11 14:06:58,264 MainThread udi_interface      INFO     __init__:<module>: Home=/home/admin
2024-01-11 14:06:58,264 MainThread udi_interface      INFO     __init__:<module>: Node Server Path=/usr/home/admin/workspace/plugin-dev/audio-player
2024-01-11 14:06:58,265 MainThread udi_interface      INFO     __init__:<module>: PG3INIT=eyJ1dWlkIjoiMDA6MjE6Yjk6MjY6MjY6MjYiLCJwcm9maWxlTnVtIjoyLCJsb2dMZXZlbCI6IklORk8iLCJ0b2tlbiI6ImMmODAtY1psQjRNQ1RQVU8iLCJtcXR0SG9zdCI6ImxvY2FsaG9zdCIsIm1xdHRQb3J0Ijo4ODgzLCJzZWN1cmUiOjEsImlzUEczeCI6dHJ1ZSwicGczVmVyc2lvbiI6IjMuMi4xNyIsImlzeVZlcnNpb24iOiI1LjguMCIsImVkaXRpb24iOiJGcmVlIn0=
2024-01-11 14:06:58,265 MainThread udi_interface      INFO     __init__:<module>: Loading interface module
2024-01-11 14:06:58,457 MainThread udi_interface      INFO     interface:<module>: Loading MQTT module
2024-01-11 14:06:58,499 MainThread udi_interface      INFO     interface:<module>: MQTT module loaded
2024-01-11 14:06:59,282 MainThread udi_interface      INFO     __init__:<module>: Loading udi_interface module
2024-01-11 14:06:59,284 MainThread udi_interface      INFO     __init__:<module>: Loading node module
2024-01-11 14:06:59,284 MainThread udi_interface      INFO     __init__:<module>: Loading custom module
2024-01-11 14:06:59,284 MainThread udi_interface      INFO     __init__:<module>: Loading isy module
2024-01-11 14:06:59,284 MainThread udi_interface      INFO     __init__:<module>: UDI interface initialized
2024-01-11 14:06:59,285 MainThread udi_interface      INFO     __init__:<module>: UDI Python Interface for Polyglot version 3 3.2.2 Starting...
2024-01-11 14:06:59,336 MainThread udi_interface.interface INFO     interface:__init__: Initialization received from Polyglot V3 3.2.17  [ISY: 5.8.0, Slot: 2]
2024-01-11 14:06:59,337 MainThread udi_interface.interface INFO     interface:__init__: Connect: Network Interface: {'addr': '172.26.18.3', 'netmask': '255.255.255.0', 'broadcast': '172.26.18.255'}
2024-01-11 14:06:59,339 MainThread udi_interface.interface WARNING  interface:_get_server_data: get_server_data: failed to read file server.json: [Errno 2] No such file or directory: 'server.json'
2024-01-11 14:06:59,340 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:06:59,341 Interface  udi_interface.interface INFO     interface:_startMqtt: Connecting to MQTT... localhost:8883
2024-01-11 14:06:59,342 Interface  udi_interface.interface INFO     interface:_startMqtt: Using SSL cert: 0021b9262626_2.cert key: 0021b9262626_2.key ca: /usr/local/etc/ssl/certs/ud.ca.cert
2024-01-11 14:06:59,397 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Connected with result code 0 (Success)
2024-01-11 14:06:59,399 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Subscribing to topic: udi/pg3/ns/clients/00:21:b9:26:26:26_2 -  MID: 2 Result: 0
2024-01-11 14:06:59,439 MQTT       udi_interface.interface INFO     interface:_subscribe: MQTT Subscribed Succesfully for Message ID: 2 - QoS: (0,)
2024-01-11 14:07:02,381 Thread-6   udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2024-01-11 14:07:02,382 Thread-6   udi_interface      INFO     audio-player:parameterHandler: we are using ./sounds as path
2024-01-11 14:07:02,382 Thread-6   udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2024-01-11 14:07:02,384 Thread-6   udi_interface.interface INFO     interface:updateProfile: Sending Install Profile command to Polyglot.
2024-01-11 14:07:02,396 MQTT       udi_interface.interface INFO     interface:_message: custom data response {'customparamsdoc': ''}
2024-01-11 14:07:02,435 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = customparamsdoc
2024-01-11 14:07:02,477 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = notices
2024-01-11 14:07:02,479 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = notices
2024-01-11 14:07:02,547 MQTT       udi_interface.interface INFO     interface:_message: Profile installation finished
2024-01-11 14:07:06,208 Thread-6   udi_interface      INFO     audio-player:addAudioNode: Adding AudioPlayer node
2024-01-11 14:07:06,210 Thread-6   udi_interface.interface INFO     interface:addNode: Adding node AudioPlayer(0) [None]
2024-01-11 14:07:06,536 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: ST to 0 UOM 25
2024-01-11 14:07:06,576 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: GV0 to 0 UOM 25
2024-01-11 14:07:14,597 Command    udi_interface      INFO     audio-player:processCommand: Got command: {'address': '0', 'cmd': 'PLAY', 'query': {'PLAYLIST.uom25': '4'}}
2024-01-11 14:07:14,598 Command    udi_interface      INFO     audio-player:processCommand: Playing #4:./sounds/fantasy.mp3
2024-01-11 14:08:13,147 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2024-01-11 14:08:13,149 MainThread udi_interface      INFO     __init__:<module>: UDI interface initializing
2024-01-11 14:08:13,150 MainThread udi_interface      INFO     __init__:<module>: User=admin
2024-01-11 14:08:13,153 MainThread udi_interface      INFO     __init__:<module>: Home=/home/admin
2024-01-11 14:08:13,154 MainThread udi_interface      INFO     __init__:<module>: Node Server Path=/usr/home/admin/workspace/plugin-dev/audio-player
2024-01-11 14:08:13,155 MainThread udi_interface      INFO     __init__:<module>: PG3INIT=eyJ1dWlkIjoiMDA6MjE6Yjk6MjY6MjY6MjYiLCJwcm9maWxlTnVtIjoyLCJsb2dMZXZlbCI6IklORk8iLCJ0b2tlbiI6ImMmODAtY1psQjRNQ1RQVU8iLCJtcXR0SG9zdCI6ImxvY2FsaG9zdCIsIm1xdHRQb3J0Ijo4ODgzLCJzZWN1cmUiOjEsImlzUEczeCI6dHJ1ZSwicGczVmVyc2lvbiI6IjMuMi4xNyIsImlzeVZlcnNpb24iOiI1LjguMCIsImVkaXRpb24iOiJGcmVlIn0=
2024-01-11 14:08:13,155 MainThread udi_interface      INFO     __init__:<module>: Loading interface module
2024-01-11 14:08:13,357 MainThread udi_interface      INFO     interface:<module>: Loading MQTT module
2024-01-11 14:08:13,388 MainThread udi_interface      INFO     interface:<module>: MQTT module loaded
2024-01-11 14:08:14,002 MainThread udi_interface      INFO     __init__:<module>: Loading udi_interface module
2024-01-11 14:08:14,004 MainThread udi_interface      INFO     __init__:<module>: Loading node module
2024-01-11 14:08:14,004 MainThread udi_interface      INFO     __init__:<module>: Loading custom module
2024-01-11 14:08:14,004 MainThread udi_interface      INFO     __init__:<module>: Loading isy module
2024-01-11 14:08:14,004 MainThread udi_interface      INFO     __init__:<module>: UDI interface initialized
2024-01-11 14:08:14,005 MainThread udi_interface      INFO     __init__:<module>: UDI Python Interface for Polyglot version 3 3.2.2 Starting...
2024-01-11 14:08:14,043 MainThread udi_interface.interface INFO     interface:__init__: Initialization received from Polyglot V3 3.2.17  [ISY: 5.8.0, Slot: 2]
2024-01-11 14:08:14,044 MainThread udi_interface.interface INFO     interface:__init__: Connect: Network Interface: {'addr': '172.26.18.3', 'netmask': '255.255.255.0', 'broadcast': '172.26.18.255'}
2024-01-11 14:08:14,046 MainThread udi_interface.interface WARNING  interface:_get_server_data: get_server_data: failed to read file server.json: [Errno 2] No such file or directory: 'server.json'
2024-01-11 14:08:14,047 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:08:14,048 Interface  udi_interface.interface INFO     interface:_startMqtt: Connecting to MQTT... localhost:8883
2024-01-11 14:08:14,048 Interface  udi_interface.interface INFO     interface:_startMqtt: Using SSL cert: 0021b9262626_2.cert key: 0021b9262626_2.key ca: /usr/local/etc/ssl/certs/ud.ca.cert
2024-01-11 14:08:14,098 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Connected with result code 0 (Success)
2024-01-11 14:08:14,100 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Subscribing to topic: udi/pg3/ns/clients/00:21:b9:26:26:26_2 -  MID: 2 Result: 0
2024-01-11 14:08:14,140 MQTT       udi_interface.interface INFO     interface:_subscribe: MQTT Subscribed Succesfully for Message ID: 2 - QoS: (0,)
2024-01-11 14:08:17,099 Thread-6   udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2024-01-11 14:08:17,100 Thread-6   udi_interface      INFO     audio-player:parameterHandler: we are using ./sounds as path
2024-01-11 14:08:17,101 Thread-6   udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2024-01-11 14:08:17,102 Thread-6   udi_interface.interface INFO     interface:updateProfile: Sending Install Profile command to Polyglot.
2024-01-11 14:08:17,103 Thread-6   udi_interface      INFO     audio-player:addAudioNode: Adding AudioPlayer node
2024-01-11 14:08:17,105 Thread-6   udi_interface.interface INFO     interface:addNode: Adding node AudioPlayer(0) [None]
2024-01-11 14:08:17,111 MQTT       udi_interface.interface INFO     interface:_message: custom data response {'customparamsdoc': ''}
2024-01-11 14:08:17,111 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = customparamsdoc
2024-01-11 14:08:17,192 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = notices
2024-01-11 14:08:17,193 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = notices
2024-01-11 14:08:17,278 MQTT       udi_interface.interface INFO     interface:_message: Profile installation finished
2024-01-11 14:08:17,432 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: ST to 0 UOM 25
2024-01-11 14:08:17,473 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: GV0 to 0 UOM 25
2024-01-11 14:08:21,211 Command    udi_interface      INFO     audio-player:processCommand: Got command: {'address': '0', 'cmd': 'PLAY', 'query': {'PLAYLIST.uom25': '4'}}
2024-01-11 14:08:21,212 Command    udi_interface      INFO     audio-player:processCommand: Playing #4:./sounds/fantasy.mp3
2024-01-11 14:08:29,001 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: ST to 1 UOM 25
2024-01-11 14:08:29,038 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: GV0 to 4 UOM 25
2024-01-11 14:08:32,039 Thread-9   udi_interface      INFO     audio-player:poll: short poll
2024-01-11 14:08:46,542 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: ST to 0 UOM 25
2024-01-11 14:08:46,626 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: GV0 to 0 UOM 25
2024-01-11 14:09:32,039 Thread-10  udi_interface      INFO     audio-player:poll: short poll
2024-01-11 14:09:47,190 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2024-01-11 14:09:47,194 MainThread udi_interface      INFO     __init__:<module>: UDI interface initializing
2024-01-11 14:09:47,195 MainThread udi_interface      INFO     __init__:<module>: User=admin
2024-01-11 14:09:47,196 MainThread udi_interface      INFO     __init__:<module>: Home=/home/admin
2024-01-11 14:09:47,197 MainThread udi_interface      INFO     __init__:<module>: Node Server Path=/usr/home/admin/workspace/plugin-dev/audio-player
2024-01-11 14:09:47,198 MainThread udi_interface      INFO     __init__:<module>: PG3INIT=eyJ1dWlkIjoiMDA6MjE6Yjk6MjY6MjY6MjYiLCJwcm9maWxlTnVtIjoyLCJsb2dMZXZlbCI6IklORk8iLCJ0b2tlbiI6ImMmODAtY1psQjRNQ1RQVU8iLCJtcXR0SG9zdCI6ImxvY2FsaG9zdCIsIm1xdHRQb3J0Ijo4ODgzLCJzZWN1cmUiOjEsImlzUEczeCI6dHJ1ZSwicGczVmVyc2lvbiI6IjMuMi4xNyIsImlzeVZlcnNpb24iOiI1LjguMCIsImVkaXRpb24iOiJGcmVlIn0=
2024-01-11 14:09:47,199 MainThread udi_interface      INFO     __init__:<module>: Loading interface module
2024-01-11 14:09:47,421 MainThread udi_interface      INFO     interface:<module>: Loading MQTT module
2024-01-11 14:09:47,452 MainThread udi_interface      INFO     interface:<module>: MQTT module loaded
2024-01-11 14:09:48,102 MainThread udi_interface      INFO     __init__:<module>: Loading udi_interface module
2024-01-11 14:09:48,104 MainThread udi_interface      INFO     __init__:<module>: Loading node module
2024-01-11 14:09:48,104 MainThread udi_interface      INFO     __init__:<module>: Loading custom module
2024-01-11 14:09:48,104 MainThread udi_interface      INFO     __init__:<module>: Loading isy module
2024-01-11 14:09:48,105 MainThread udi_interface      INFO     __init__:<module>: UDI interface initialized
2024-01-11 14:09:48,105 MainThread udi_interface      INFO     __init__:<module>: UDI Python Interface for Polyglot version 3 3.2.2 Starting...
2024-01-11 14:09:48,125 MainThread udi_interface.interface INFO     interface:__init__: Initialization received from Polyglot V3 3.2.17  [ISY: 5.8.0, Slot: 2]
2024-01-11 14:09:48,125 MainThread udi_interface.interface INFO     interface:__init__: Connect: Network Interface: {'addr': '172.26.18.3', 'netmask': '255.255.255.0', 'broadcast': '172.26.18.255'}
2024-01-11 14:09:48,128 MainThread udi_interface.interface WARNING  interface:_get_server_data: get_server_data: failed to read file server.json: [Errno 2] No such file or directory: 'server.json'
2024-01-11 14:09:48,128 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': '1.0.2', 'requestId': False}}
2024-01-11 14:09:48,129 Interface  udi_interface.interface INFO     interface:_startMqtt: Connecting to MQTT... localhost:8883
2024-01-11 14:09:48,130 Interface  udi_interface.interface INFO     interface:_startMqtt: Using SSL cert: 0021b9262626_2.cert key: 0021b9262626_2.key ca: /usr/local/etc/ssl/certs/ud.ca.cert
2024-01-11 14:09:48,181 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Connected with result code 0 (Success)
2024-01-11 14:09:48,183 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Subscribing to topic: udi/pg3/ns/clients/00:21:b9:26:26:26_2 -  MID: 2 Result: 0
2024-01-11 14:09:48,224 MQTT       udi_interface.interface INFO     interface:_subscribe: MQTT Subscribed Succesfully for Message ID: 2 - QoS: (0,)
2024-01-11 14:09:51,182 Thread-6   udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2024-01-11 14:09:51,184 Thread-6   udi_interface      INFO     audio-player:parameterHandler: we are using ./sounds as path
2024-01-11 14:09:51,184 Thread-6   udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2024-01-11 14:09:51,186 Thread-6   udi_interface.interface INFO     interface:updateProfile: Sending Install Profile command to Polyglot.
2024-01-11 14:09:51,186 Thread-6   udi_interface      INFO     audio-player:addAudioNode: Adding AudioPlayer node
2024-01-11 14:09:51,188 Thread-6   udi_interface.interface INFO     interface:addNode: Adding node AudioPlayer(0) [None]
2024-01-11 14:09:51,192 MQTT       udi_interface.interface INFO     interface:_message: custom data response {'customparamsdoc': ''}
2024-01-11 14:09:51,197 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = customparamsdoc
2024-01-11 14:09:51,274 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = notices
2024-01-11 14:09:51,276 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = notices
2024-01-11 14:09:51,359 MQTT       udi_interface.interface INFO     interface:_message: Profile installation finished
2024-01-11 14:09:51,517 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: ST to 0 UOM 25
2024-01-11 14:09:51,557 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: GV0 to 0 UOM 25
2024-01-11 14:10:04,591 Command    udi_interface      INFO     audio-player:processCommand: Got command: {'address': '0', 'cmd': 'PLAY', 'query': {'PLAYLIST.uom25': '1'}}
2024-01-11 14:10:04,593 Command    udi_interface      INFO     audio-player:processCommand: Playing #1:./sounds/bells2.mp3
2024-01-11 14:10:06,498 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: ST to 1 UOM 25
2024-01-11 14:10:06,531 MQTT       udi_interface.interface INFO     interface:_message: Successfully set 0 :: GV0 to 1 UOM 25
